import { ImageSourcePropType } from 'react-native';

const JOKER_PREVIEW_IMAGES: Record<string, ImageSourcePropType> = {
  pair_savings: require('../assets/jokers/joker-pair-savings-character.png'),
  twin_engine: require('../assets/jokers/joker-twin-engine-character.png'),
  house_keeper: require('../assets/jokers/joker-house-keeper-character.png'),
  straight_scholar: require('../assets/jokers/joker-straight-scholar-character.png'),
  six_cult: require('../assets/jokers/joker-six-cult-character.png'),
  card_sharp: require('../assets/jokers/joker-card-sharp-character.png'),
  burn_count: require('../assets/jokers/joker-burn-count-character.png'),
  reroll_ledger: require('../assets/jokers/joker-reroll-ledger-character.png'),
  perfect_grip: require('../assets/jokers/joker-perfect-grip-character.png'),
  piggy_bank: require('../assets/jokers/joker-piggy-bank-character.png'),
  golden_habit: require('../assets/jokers/joker-golden-habit-character.png'),
  frugal_mask: require('../assets/jokers/joker-frugal-mask-character.png'),
  all_in: require('../assets/jokers/joker-all-in-character.png'),
  glass_joker: require('../assets/jokers/joker-glass-joker-character.png'),
  last_chance: require('../assets/jokers/joker-last-chance-character.png'),
  gold_rush: require('../assets/jokers/joker-gold-rush-character.png'),
  heavy_purse: require('../assets/jokers/joker-heavy-purse-character.png'),
  loose_change: require('../assets/jokers/joker-loose-change-character.png'),
  pawn_broker: require('../assets/jokers/joker-pawn-broker-character.png'),
  golden_nerves: require('../assets/jokers/joker-golden-nerves-character.png'),
  tax_collector: require('../assets/jokers/joker-tax-collector-character.png'),
  bribe: require('../assets/jokers/joker-bribe-character.png'),
  jackpot_engine: require('../assets/jokers/joker-jackpot-engine-character.png'),
  black_market_smile: require('../assets/jokers/joker-black-market-smile-character.png'),
  six_master: require('../assets/jokers/joker-six-master-character.png'),
  steady_pair: require('../assets/jokers/joker-steady-pair-character.png'),
  lucky_reroll: require('../assets/jokers/joker-lucky-reroll-character.png'),
  golden_touch: require('../assets/jokers/joker-golden-touch-character.png'),
  even_power: require('../assets/jokers/joker-even-power-character.png'),
  even_polish: require('../assets/jokers/joker-even-polish-character.png'),
  odd_power: require('../assets/jokers/joker-odd-power-character.png'),
  triple_boost: require('../assets/jokers/joker-triple-boost-character.png'),
  straight_spark: require('../assets/jokers/joker-straight-spark-character.png'),
  full_grip: require('../assets/jokers/joker-full-grip-character.png'),
  fresh_deal: require('../assets/jokers/joker-fresh-deal-character.png'),
  shop_6_slot: require('../assets/jokers/joker-market-expansion-character.png'),
  gap_draw: require('../assets/jokers/joker-gap-fill-character.png'),
  sixth_sense: require('../assets/jokers/joker-sixth-sense-character.png'),
};

export const getJokerPreviewImage = (jokerId: string): ImageSourcePropType | undefined =>
  JOKER_PREVIEW_IMAGES[jokerId];
